services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    command: ["server", "/data", "--console-address", ":9001"]

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    command: ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  forwarding:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "-m", "app.queueing.forwarding"]

  ocr:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "-m", "app.ocr.main"]

  filtering:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "-m", "app.filter.filtering"]
